import type { Metadata } from "next";
import { PropsWithChildren } from "react";

import { poppins } from "@/styles/fonts/fonts";
import { Header } from "@/components/header/header";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />

        <main>{children}</main>
      </body>
    </html>
  );
}
